# Generated by Django 3.2.3 on 2021-05-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0002_count_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count_model',
            name='word',
        ),
    ]
